# Harmony Jekyll theme general configurations 

# Base URL
baseurl: 

# S3 URL
url: http://sameersoi.com

# Localhost 
#url: http://127.0.0.1:4000

# Personal webite
harmony:
  name: Sameer Soi
  # Little description about your site
  description: A data scientist in Kings county.
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and 
  # in your feed.xml site description.
  meta_description: Sameer is a full-stack data scientist with experience and a love for prototyping, productionizing, and deploying data-driven solutions
  basetheme: blue-water # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Sameer Soi
    email: mail@sameersoi.com
    url: http://www.sameersoi.com

  # Google Analytics key, leave blank to ignore
  google_analytics_key:

  # Profile links, leave blank to ignore
  social: 
    github: ssoi
    twitter: sameersoi 
    gplus: 112797866865058191852
  show_disclaimer: true

# Conversion / Build settings 
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: rouge

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
